# Generated by Django 3.2.4 on 2021-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variety', models.CharField(max_length=200)),
                ('commodity_type', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('ExtBag', 'Ext Bag'), ('MedBunch', 'Med Bunch'), ('LgBox', 'Lg Box'), ('Bag', 'Bag'), ('SmBasket', 'Sm Basket'), ('net', 'net'), ('Dozen', 'Dozen'), ('crate', 'crate')], max_length=20)),
                ('volume_in_kgs', models.PositiveIntegerField()),
                ('values_in_ksh', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.FloatField()),
            ],
        ),
    ]
