# Generated by Django 3.2.4 on 2021-06-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='object_id',
        ),
    ]
