# Generated by Django 3.2.4 on 2021-06-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_details', '0002_remove_crops_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='values_in_ksh',
            field=models.PositiveIntegerField(),
        ),
    ]
