# Generated by Django 3.2.4 on 2021-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_details', '0003_alter_crops_values_in_ksh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='values_in_ksh',
            field=models.FloatField(),
        ),
    ]
