# Generated by Django 3.2.4 on 2021-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_details', '0004_alter_crops_values_in_ksh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='values_in_ksh',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
