# Generated by Django 3.2.4 on 2021-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_details', '0005_alter_crops_values_in_ksh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
